[project]
name = "sketchy-svg"
version = "0.2.3"
description = "A png drawing to svg converter"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "anywidget>=0.9.21",
    "marimo>=0.20.1",
    "matplotlib>=3.8.0",
    "mpld3>=0.5.12",
    "networkx>=3.4.2",
    "numpy",
    "pillow>=10.2.0",
    "pytest>=9.0.2",
    "python-dotenv>=1.2.1",
    "scikit-image>=0.20.0",
    "traitlets>=5.14.3",
]

[project.scripts]
cli = "sketchy:cli"


[build-system]
requires = ["uv_build>=0.8.4,<0.9.0"]
build-backend = "uv_build"

[dependency-groups]
# if you want to train the CNN
train = [
    "torch",
    "torchvision",
    "perlin-numpy>=0.0.1",
    "polars>=1.38.1",
    "cairosvg>=2.8.2",
    "onnx>=1.18.0",
]
onnx = [
    "onnxruntime>=1.22.1",
]
# linter and type checker
dev = [
    "ty>=0.0.1a16",
    "marimo>=0.19.9",
    "ruff",
    "nbformat>=5.10.4",
]
